env:
  SERVER_TAG: ghcr.io/eclipse/openvsx-server
  WEBUI_TAG: ghcr.io/eclipse/openvsx-webui
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - continue-on-error: true
      name: Install Yarn
      run: 'corepack enable

        corepack prepare yarn@stable --activate

        '
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set Image Version
      run: echo "IMAGE_VERSION=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
    - continue-on-error: true
      name: Build CLI
      run: yarn --cwd cli
    - continue-on-error: true
      name: Build Web UI Image
      run: docker build -t $WEBUI_TAG:$IMAGE_VERSION webui
    - continue-on-error: true
      name: Run Server Tests
      run: server/gradlew --no-daemon -p server check
    - continue-on-error: true
      name: Build Server Image
      run: docker build -t $SERVER_TAG:$IMAGE_VERSION server
    - continue-on-error: true
      if: github.repository == 'eclipse/openvsx' && github.ref == 'refs/heads/master'
      name: Push Docker Images
      run: 'echo ${{ secrets.BOT_ACCESS_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR
        --password-stdin

        docker push $SERVER_TAG:$IMAGE_VERSION

        docker push $WEBUI_TAG:$IMAGE_VERSION

        '
    - continue-on-error: true
      if: github.event_name == 'pull_request'
      name: Save PR number to file
      run: echo ${{ github.event.number }} > PR_NUMBER.txt
    - continue-on-error: true
      if: github.event_name == 'pull_request'
      name: Archive PR number
      uses: actions/upload-artifact@v3
      with:
        name: PR_NUMBER
        path: PR_NUMBER.txt
name: CI
on:
  repository_dispatch:
    types: trigger-ga___main.yml
