env:
  SERVER_TAG: ghcr.io/eclipse/openvsx-server
  WEBUI_TAG: ghcr.io/eclipse/openvsx-webui
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set Image Version
      run: echo "IMAGE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
    - continue-on-error: true
      name: Build Web UI Image
      run: docker build -t $WEBUI_TAG:$IMAGE_VERSION webui
    - continue-on-error: true
      name: Build Server Image
      run: docker build -t $SERVER_TAG:$IMAGE_VERSION server
    - continue-on-error: true
      name: Push Docker Images
      run: 'echo ${{ secrets.BOT_ACCESS_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR
        --password-stdin

        docker push $SERVER_TAG:$IMAGE_VERSION

        docker push $WEBUI_TAG:$IMAGE_VERSION

        '
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
